import { BarChart3, FileText } from "lucide-react";
import { useLanguage } from "@/contexts/LanguageContext";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from "recharts";

const t = {
  title: { es: "REPORTES", en: "REPORTS" },
  subtitle: { es: "Informes por período", en: "Period reports" },
  stats: {
    income: { es: "Ingresos del mes", en: "Monthly income" },
    delivered: { es: "Proyectos entregados", en: "Projects delivered" },
    closeRate: { es: "Tasa de cierre", en: "Close rate" },
    topService: { es: "Servicio más vendido", en: "Top selling service" },
  },
  cols: {
    period: { es: "Período", en: "Period" },
    type: { es: "Tipo", en: "Type" },
    by: { es: "Generado por", en: "Generated by" },
    date: { es: "Fecha", en: "Date" },
    action: { es: "Acción", en: "Action" },
  },
  chartTitle: { es: "Ingresos por servicio", en: "Revenue by service" },
  viewPdf: { es: "Ver PDF", en: "View PDF" },
};

const statsData = [
  { label: t.stats.income, value: "$22,500", color: "#4ADB7A" },
  { label: t.stats.delivered, value: "1", color: "#4A9EDB" },
  { label: t.stats.closeRate, value: "37.5%", color: "#D4A84B" },
  { label: t.stats.topService, value: "E-commerce", color: "#E53E3E" },
];

const reports = [
  { period: { es: "Marzo 2026", en: "March 2026" }, type: { es: "Mensual", en: "Monthly" }, by: "Olivia", date: "01/03/2026" },
  { period: { es: "Febrero 2026", en: "February 2026" }, type: { es: "Mensual", en: "Monthly" }, by: "Ali", date: "01/02/2026" },
  { period: { es: "Q4 2025", en: "Q4 2025" }, type: { es: "Trimestral", en: "Quarterly" }, by: "Olivia", date: "05/01/2026" },
  { period: { es: "Enero 2026", en: "January 2026" }, type: { es: "Mensual", en: "Monthly" }, by: "Rodrigo", date: "01/01/2026" },
  { period: { es: "2025 Anual", en: "2025 Annual" }, type: { es: "Anual", en: "Annual" }, by: "Olivia", date: "15/01/2026" },
];

const chartData = [
  { name: "E-commerce", value: 35000 },
  { name: "SaaS", value: 22000 },
  { name: "Landing Pages", value: 18000 },
  { name: { es: "Mantenimiento", en: "Maintenance" }, value: 12000 },
  { name: "Branding", value: 8000 },
];

const barColors = ["#E53E3E", "#4A9EDB", "#D4A84B", "#4ADB7A", "#9B87F5"];

const ReportesPage = () => {
  const { lang } = useLanguage();

  return (
    <div className="space-y-6">
      <div>
        <div className="flex items-center gap-3 mb-1">
          <BarChart3 size={22} style={{ color: "var(--nebu-accent)" }} />
          <h1 className="text-2xl font-bold tracking-tight" style={{ color: "var(--nebu-text)" }}>{t.title[lang]}</h1>
        </div>
        <p className="text-sm" style={{ color: "var(--nebu-text-secondary)" }}>{t.subtitle[lang]}</p>
      </div>

      {/* Stats */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {statsData.map((s, i) => (
          <div key={i} className="rounded-lg p-4" style={{ backgroundColor: "var(--nebu-card)", border: "1px solid var(--nebu-border)" }}>
            <p className="text-xs mb-1" style={{ color: "var(--nebu-text-secondary)" }}>{s.label[lang]}</p>
            <p className="text-xl font-bold" style={{ color: s.color }}>{s.value}</p>
          </div>
        ))}
      </div>

      {/* Reports table */}
      <div className="rounded-lg overflow-hidden" style={{ border: "1px solid var(--nebu-border)" }}>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead>
              <tr style={{ backgroundColor: "var(--nebu-surface)" }}>
                {Object.values(t.cols).map((col, i) => (
                  <th key={i} className="px-4 py-3 text-left text-xs font-semibold uppercase tracking-wider" style={{ color: "var(--nebu-text-secondary)", borderBottom: "1px solid var(--nebu-border)" }}>{col[lang]}</th>
                ))}
              </tr>
            </thead>
            <tbody>
              {reports.map((r, i) => (
                <tr key={i} style={{ backgroundColor: "var(--nebu-card)", borderBottom: "1px solid var(--nebu-border)" }}>
                  <td className="px-4 py-3 font-medium" style={{ color: "var(--nebu-text)" }}>{r.period[lang]}</td>
                  <td className="px-4 py-3" style={{ color: "var(--nebu-text-secondary)" }}>{r.type[lang]}</td>
                  <td className="px-4 py-3" style={{ color: "var(--nebu-text)" }}>{r.by}</td>
                  <td className="px-4 py-3" style={{ color: "var(--nebu-text-secondary)" }}>{r.date}</td>
                  <td className="px-4 py-3">
                    <button className="flex items-center gap-1 text-xs font-medium px-2.5 py-1 rounded-md transition-colors" style={{ backgroundColor: "var(--nebu-surface)", border: "1px solid var(--nebu-border)", color: "var(--nebu-text-secondary)" }}>
                      <FileText size={12} /> {t.viewPdf[lang]}
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Chart */}
      <div className="rounded-lg p-5" style={{ backgroundColor: "var(--nebu-card)", border: "1px solid var(--nebu-border)" }}>
        <h3 className="text-sm font-semibold mb-4" style={{ color: "var(--nebu-text)" }}>{t.chartTitle[lang]}</h3>
        <ResponsiveContainer width="100%" height={250}>
          <BarChart data={chartData.map(d => ({ ...d, name: typeof d.name === "string" ? d.name : d.name[lang] }))} layout="vertical" margin={{ left: 20 }}>
            <XAxis type="number" tick={{ fill: "#888888", fontSize: 11 }} tickFormatter={(v) => `$${(v / 1000).toFixed(0)}k`} />
            <YAxis type="category" dataKey="name" tick={{ fill: "#888888", fontSize: 11 }} width={110} />
            <Tooltip formatter={(v: number) => [`$${v.toLocaleString()}`, ""]} contentStyle={{ backgroundColor: "#1a1a1a", border: "1px solid #2a2a2a", borderRadius: 8, color: "#fff" }} />
            <Bar dataKey="value" radius={[0, 4, 4, 0]}>
              {chartData.map((_, i) => <Cell key={i} fill={barColors[i]} />)}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>
    </div>
  );
};

export default ReportesPage;
