import { Home, Briefcase, GitBranch, Wrench, DollarSign } from "lucide-react";

export type Page = "dashboard" | "proyectos" | "pipeline" | "herramientas" | "finanzas";

interface AppSidebarProps {
  activePage: Page;
    onNavigate: (page: Page) => void;
      open: boolean;
        onClose: () => void;
        }

        const navItems: { id: Page; label: string; icon: React.ElementType }[] = [
          { id: "dashboard", label: "Dashboard", icon: Home },
            { id: "proyectos", label: "Proyectos", icon: Briefcase },
              { id: "pipeline", label: "Pipeline", icon: GitBranch },
                { id: "herramientas", label: "Herramientas", icon: Wrench },
                  { id: "finanzas", label: "Finanzas", icon: DollarSign },
                  ];

                  const AppSidebar = ({ activePage, onNavigate, open, onClose }: AppSidebarProps) => {
                    return (
                        <>
                              {/* Mobile overlay */}
                                    {open && (
                                            <div
                                                      className="fixed inset-0 bg-black/60 z-40 lg:hidden"
                                                                onClick={onClose}
                                                                        />
                                                                              )}

                                                                                    <aside
                                                                                            className={`
                                                                                                      fixed lg:static top-0 left-0 z-50
                                                                                                                h-full w-[240px] flex flex-col
                                                                                                                          border-r
                                                                                                                                    transition-transform duration-200
                                                                                                                                              ${open ? "translate-x-0" : "-translate-x-full lg:translate-x-0"}
                                                                                                                                                      `}
                                                                                                                                                              style={{
                                                                                                                                                                        backgroundColor: "var(--nebu-surface)",
                                                                                                                                                                                  borderColor: "var(--nebu-border)",
                                                                                                                                                                                          }}
                                                                                                                                                                                                >
                                                                                                                                                                                                        {/* Logo */}
                                                                                                                                                                                                                <div
                                                                                                                                                                                                                          className="h-16 flex items-center px-6 shrink-0"
                                                                                                                                                                                                                                    style={{ borderBottom: "1px solid var(--nebu-border)" }}
                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                      <span
                                                                                                                                                                                                                                                                  className="text-2xl font-bold tracking-tight"
                                                                                                                                                                                                                                                                              style={{ color: "var(--nebu-accent)" }}
                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                    NEBU
                                                                                                                                                                                                                                                                                                              </span>
                                                                                                                                                                                                                                                                                                                      </div>

                                                                                                                                                                                                                                                                                                                              {/* Navigation */}
                                                                                                                                                                                                                                                                                                                                      <nav className="flex-1 overflow-y-auto py-4 px-3 space-y-1">
                                                                                                                                                                                                                                                                                                                                                {navItems.map((item) => {
                                                                                                                                                                                                                                                                                                                                                            const active = activePage === item.id;
                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                      key={item.id}
                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={() => {
                                                                                                                                                                                                                                                                                                                                                                                                                                        onNavigate(item.id);
                                                                                                                                                                                                                                                                                                                                                                                                                                                          onClose();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          className="w-full flex items-center gap-3 px-3 py-2.5 rounded-md text-sm transition-all duration-150"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            backgroundColor: active ? "var(--nebu-active-bg)" : "transparent",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              color: active ? "var(--nebu-accent)" : "var(--nebu-text-secondary)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              onMouseEnter={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!active) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    e.currentTarget.style.backgroundColor = "var(--nebu-card)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        e.currentTarget.style.color = "var(--nebu-text)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          onMouseLeave={(e) => {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (!active) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                e.currentTarget.style.backgroundColor = "transparent";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    e.currentTarget.style.color = "var(--nebu-text-secondary)";
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <item.icon size={18} />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <span className={active ? "font-semibold" : "font-normal"}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      {item.label}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          })}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </nav>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          {/* Footer */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <div
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="px-6 py-4 text-xs shrink-0"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      style={{
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  color: "var(--nebu-text-secondary)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              borderTop: "1px solid var(--nebu-border)",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          Nebu Studio CRM v1.0
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </aside>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              };

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              export default AppSidebar;